using System;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MySql;
using MySql.Data.MySqlClient;
using Npgsql;



namespace NESTExportaDB
{
	public class ClienteBanco
	{
		#region Public-Members

		/// <summary>
		/// The connection string used to connect to the database server.
		/// </summary>
		public string ConnectionString { get; private set; }

		/// <summary>
		/// Enable or disable console logging of raw queries generated by the library.
		/// </summary>
		public bool DebugRawQuery = false;

		/// <summary>
		/// Enable or disable console logging of returned row counts for successful queries run by the library.
		/// </summary>
		public bool DebugResultRowCount = false;

		public List<Tabela> Tabelas
		{
			get { return mTabelas; }

		}

		#endregion

		#region Private-Members

		private bool _Disposed = false;

		private DbTypes _DbType;
		private string _ServerIp;
		private int _ServerPort;
		private string _Username;
		private string _Password;
		private string _Instance;
		private string _DatabaseName;
		private string _NoDataTables;
		private Dictionary<string, List<string>> _TablesIdsSorted = new Dictionary<string, List<string>>();

		private readonly object _LoadingTablesLock = new object();
		private ListaConcorrente<string> _TableNames = new ListaConcorrente<string>();
		private ListaConcorrente<string> _TableDependencies = new ListaConcorrente<string>();
		private ConcurrentDictionary<string, List<Coluna>> _TableDetails = new ConcurrentDictionary<string, List<Coluna>>();

		private Random _Random = new Random();
		private List<Tabela> mTabelas = new List<Tabela>();
		private List<Procedure> mProcedures = new List<Procedure>();
		#endregion

		#region Constructors-and-Factories

		/// <summary>
		/// Create an instance of the database client.
		/// </summary>
		/// <param name="dbType">The type of database.</param>
		/// <param name="serverIp">The IP address or hostname of the database server.</param>
		/// <param name="serverPort">The TCP port of the database server.</param>
		/// <param name="username">The username to use when authenticating with the database server.</param>
		/// <param name="password">The password to use when authenticating with the database server.</param>
		/// <param name="instance">The instance on the database server (for use with Microsoft SQL Server).</param>
		/// <param name="database">The name of the database with which to connect.</param>
		public ClienteBanco(
				DbTypes dbType,
				string serverIp,
				int serverPort,
				string username,
				string password,
				string instance,
				string database)
		{
			LoadParameters();
			//
			// MsSql, MySql, and PostgreSql will use server IP, port, username, password, database
			// Sqlite will use just database and it should refer to the database file
			//
			if (String.IsNullOrEmpty(serverIp)) throw new ArgumentNullException(nameof(serverIp));
			if (serverPort < 0) throw new ArgumentOutOfRangeException(nameof(serverPort));
			if (String.IsNullOrEmpty(database)) throw new ArgumentNullException(nameof(database));

			_DbType = dbType;
			_ServerIp = serverIp;
			_ServerPort = serverPort;
			_Username = username;
			_Password = password;
			_Instance = instance;
			_DatabaseName = database;

			PopulaConnectionString();
			CarregaTabelas();
			CarregaDetalhesTabela();
			CarregaProcedures();
		}

		/// <summary>
		/// Create an instance of the database client.
		/// </summary>
		/// <param name="dbType">The type of database.</param>
		/// <param name="serverIp">The IP address or hostname of the database server.</param>
		/// <param name="serverPort">The TCP port of the database server.</param>
		/// <param name="username">The username to use when authenticating with the database server.</param>
		/// <param name="password">The password to use when authenticating with the database server.</param>
		/// <param name="instance">The instance on the database server (for use with Microsoft SQL Server).</param>
		/// <param name="database">The name of the database with which to connect.</param>
		public ClienteBanco(
				string dbType,
				string serverIp,
				int serverPort,
				string username,
				string password,
				string instance,
				string database)
		{
			LoadParameters();
			//
			// MsSql, MySql, and PostgreSql will use server IP, port, username, password, database
			// Sqlite will use just database and it should refer to the database file
			//
			if (String.IsNullOrEmpty(serverIp)) throw new ArgumentNullException(nameof(serverIp));
			if (serverPort < 0) throw new ArgumentOutOfRangeException(nameof(serverPort));
			if (String.IsNullOrEmpty(database)) throw new ArgumentNullException(nameof(database));
			if (String.IsNullOrEmpty(dbType)) throw new ArgumentNullException(nameof(dbType));

			switch (dbType.ToLower())
			{
				case "mssql":
					_DbType = DbTypes.MsSql;
					break;

				case "mysql":
					_DbType = DbTypes.MySql;
					break;

				case "pgsql":
					_DbType = DbTypes.PgSql;
					break;

				default:
					throw new ArgumentOutOfRangeException(nameof(dbType));
			}

			_ServerIp = serverIp;
			_ServerPort = serverPort;
			_Username = username;
			_Password = password;
			_Instance = instance;
			_DatabaseName = database;

			PopulaConnectionString();
			CarregaTabelas();
			CarregaDetalhesTabela();
		
		}

		#endregion

		#region Public-Methods

		/// <summary>
		/// Tear down the client and dispose of resources.
		/// </summary>
		public void Dispose()
		{
			Dispose(true);
			GC.SuppressFinalize(this);
		}

		private void LoadParameters()
		{
			string line;
			string[] mParam;
			System.IO.StreamReader file =
			new System.IO.StreamReader(@"Parameters\Config.app");
			line = file.ReadLine();
			mParam = line.Split('|');
			_NoDataTables = mParam[0];
		}

		/// <summary>
		/// Show the columns and column metadata from a specific table.
		/// </summary>
		/// <param name="tableName">The table to view.</param>
		/// <returns>A list of column objects.</returns>
		public List<Coluna> DetalheTabela(string tableName)
		{
			if (String.IsNullOrEmpty(tableName)) throw new ArgumentNullException(nameof(tableName));

			List<Coluna> details;
			if (_TableDetails.TryGetValue(tableName, out details))
			{
				return details;
			}
			else
			{
				throw new Exception("Table " + tableName + " is not in the tables list");
			}
		}

		/// <summary>
		/// Retrieve the name of the primary key column from a specific table.
		/// </summary>
		/// <param name="tableName">The table of which you want the primary key.</param>
		/// <returns>A string containing the column name.</returns>
		public string ChavePrimaria(string tableName)
		{
			if (String.IsNullOrEmpty(tableName)) throw new ArgumentNullException(nameof(tableName));

			List<Coluna> details;
			if (_TableDetails.TryGetValue(tableName, out details))
			{
				if (details != null && details.Count > 0)
				{
					foreach (Coluna c in details)
					{
						if (c.IsPrimaryKey) return c.Name;
					}
				}

				throw new Exception("Unable to find primary key for table " + tableName);
			}
			else
			{
				throw new Exception("Table " + tableName + " is not in the tables list");
			}
		}

		/// <summary>
		/// Retrieve a list of the names of columns from within a specific table.
		/// </summary>
		/// <param name="tableName">The table of which ou want to retrieve the list of columns.</param>
		/// <returns>A list of strings containing the column names.</returns>
		public List<string> NomesColuna(string tableName)
		{
			if (String.IsNullOrEmpty(tableName)) throw new ArgumentNullException(nameof(tableName));

			List<Coluna> details;
			List<string> columnNames = new List<string>();

			if (_TableDetails.TryGetValue(tableName, out details))
			{
				if (details != null && details.Count > 0)
				{
					foreach (Coluna c in details)
					{
						columnNames.Add(c.Name);
					}

					return columnNames;
				}

				throw new Exception("Unable to find primary key for table " + tableName);
			}
			else
			{
				throw new Exception("Table " + tableName + " is not in the tables list");
			}
		}

		public void ScriptProcedures(string path)
		{
			StringBuilder mRetDef = new StringBuilder();
			foreach (Procedure mProc in mProcedures)
			{
				mRetDef.AppendLine("--Function/Procedure: " + mProc.Name + " \n" + mProc.Content + " \n" + ";" + "\n");

			}

			string mFileProc = string.Format(path + "{0}_{1}_{2}.sql", "PROC", _DatabaseName.ToUpper(), DateTime.Now.ToString("yyyyMMddHHmmss"));
			System.IO.File.WriteAllText(mFileProc, mRetDef.ToString());
			
		}

		public void ScriptBanco(string path)
		{
			StringBuilder mRetDef = new StringBuilder();
			StringBuilder mReConst = new StringBuilder();
			foreach (Tabela mTabela in mTabelas)
			{
				mRetDef.AppendLine(mTabela.DefinicaoTabela(false));
				mReConst.AppendLine(mTabela.ChavesTabela(false));
			}

			string mFileScript = string.Format(path + "{0}_{1}_{2}.sql", "DB", _DatabaseName.ToUpper(), DateTime.Now.ToString("yyyyMMddHHmmss"));
			System.IO.File.WriteAllText(mFileScript, mRetDef.ToString() + "\n" + mReConst.ToString());

		}

		public void ScriptDados(string path)
		{
			string mRetDef = "";
			string queryEnable = "";
			string queryDisable = "";
			StringBuilder disableConstraints = new StringBuilder();
			StringBuilder enableConstraints = new StringBuilder();
			int seq = 1;

			//CarregaDependencias();

			switch (_DbType)
			{
				case DbTypes.MsSql:
					//implementar
					break;

				case DbTypes.MySql:
					//implementar
					break;

				case DbTypes.PgSql:
					queryEnable = PgsqlHelper.EnableConstraintsQuery("NOME_TABELA");
					queryDisable = PgsqlHelper.DisableConstraintsQuery("NOME_TABELA");
					break;
			}
			OrdenaDependncias();
			
			foreach (string tableOrder in _TableDependencies)
			{
				foreach (Tabela tabDef in mTabelas) {
					if (PermiteMigrarDados(tabDef.Name) && CompareRaw( tabDef.Name , tableOrder)) 
					{
						enableConstraints.Append(queryEnable.Replace("NOME_TABELA", tabDef.Name ) + Environment.NewLine);
						disableConstraints.Append(queryDisable.Replace("NOME_TABELA", tabDef.Name ) + Environment.NewLine);

						mRetDef = CarregaDadosTabela(tabDef);
						if (!String.IsNullOrEmpty(mRetDef))
						{
							seq++;
							string mFile = string.Format(path + seq.ToString().PadLeft(4, '0') + "_REC_{0}_{1}_{2}.sql", TextRaw(tableOrder), _DatabaseName.ToUpper(), DateTime.Now.ToString("yyyyMMddHHmmss"));
							System.IO.File.WriteAllText(mFile, mRetDef);

						}
					}
				}
				
			}

			foreach (Tabela tabDef in mTabelas)
			{
				if (PermiteMigrarDados(tabDef.Name) && !_TableDependencies.Contains( TextRaw(tabDef.Name)))
				{
					enableConstraints.Append(queryEnable.Replace("NOME_TABELA", tabDef.Name ) + Environment.NewLine);
					disableConstraints.Append(queryDisable.Replace("NOME_TABELA", tabDef.Name ) + Environment.NewLine);

					mRetDef = CarregaDadosTabela(tabDef);
					if (!String.IsNullOrEmpty(mRetDef))
					{
						seq++;
						string mFile = string.Format(path + seq.ToString().PadLeft(4, '0') + "_REC_{0}_{1}_{2}.sql", TextRaw(tabDef.Name), _DatabaseName.ToUpper(), DateTime.Now.ToString("yyyyMMddHHmmss"));
						System.IO.File.WriteAllText(mFile, mRetDef);

					}
				}
			}

			for(int i = _TablesIdsSorted.Count-1; i >= 0; i--)
			{
				string tabName = _TablesIdsSorted.Keys.ElementAt(i);
				List<string> filters = _TablesIdsSorted[TextRaw(tabName)];
				string strKey = "";
				string strKeySep = "";
				string strWhere = "";
				string strWhereSep = "";
				string tabFilter = "";
				string tabFilterSep = "";
				foreach (Tabela tabDef in mTabelas)
				{
					if (PermiteMigrarDados(tabDef.Name) && CompareRaw(tabDef.Name, tabName))
					{
						tabName = tabDef.Name;
						strKey = "";
						strKeySep = "";
						strWhere = "";
						strWhereSep = "";
						tabFilter = "";
						tabFilterSep = "";
						foreach (Coluna col in tabDef.Colunas)
						{
							
							if (col.IsPrimaryKey)
							{

								strKey += strKeySep + col.Name;
								strKeySep = " , ";
								strWhere += strWhereSep + " TAB." + col.Name + " = " + tabDef.Name + "." + col.Name + Environment.NewLine;
								strWhereSep = " AND ";
							}
						}

						foreach(string filter in filters)
						{
							tabFilter += tabFilterSep + "    (" + filter + ")" +  Environment.NewLine;
							tabFilterSep = " OR ";
						}
					}
				}
				string sDel = "DELETE " + Environment.NewLine +
											"FROM " + Environment.NewLine +
											"	" + tabName + " " + Environment.NewLine +
											"WHERE " + Environment.NewLine +
											"	NOT EXISTS( " + Environment.NewLine +
											"	SELECT	" + strKey + " " + Environment.NewLine +
											"	FROM " + Environment.NewLine +
											"		(" + Environment.NewLine +
											"			SELECT 	" + strKey + " " + Environment.NewLine +
											"		FROM " + Environment.NewLine +
											"			" + tabName + " " + Environment.NewLine +
											"		WHERE " + Environment.NewLine +
											"			(	" + tabFilter + " ) " + Environment.NewLine +
											"			) TAB " + Environment.NewLine +
											"	WHERE " + Environment.NewLine +
			                  strWhere  + ");" ;

				seq++;
				string mFile = string.Format(path + seq.ToString().PadLeft(4, '0') + "_DEL_{0}_{1}_{2}.sql", TextRaw(tabName), _DatabaseName.ToUpper(), DateTime.Now.ToString("yyyyMMddHHmmss"));
				System.IO.File.WriteAllText(mFile, sDel);
			}

			string mFileName = string.Format(path +  "0001_DES_{0}_{1}_{2}.sql", "CONSTRAINTS", _DatabaseName.ToUpper(), DateTime.Now.ToString("yyyyMMddHHmmss"));
			System.IO.File.WriteAllText(mFileName, disableConstraints.ToString());

			mFileName = string.Format(path + seq.ToString().PadLeft(4, '0') + "_HAB_{0}_{1}_{2}.sql", "CONSTRAINTS", _DatabaseName.ToUpper(), DateTime.Now.ToString("yyyyMMddHHmmss"));
			System.IO.File.WriteAllText(mFileName, enableConstraints.ToString());

		}

		public void ImportaDados(string path)
		{
			foreach (string file in System.IO.Directory.EnumerateFiles(path, "*.sql"))
			{
				string contents = System.IO.File.ReadAllText(file);
				NoQueryy(contents);
				System.IO.File.Move(file, file.Replace(".sql", ".old"));
			}
		}

		private bool CompareRaw(string text1 , string text2)
		{
			return (TextRaw( text1)==  TextRaw( text2) );
		}

		private string TextRaw(string text)
		{
			return text.Replace("\"", "");
		}
		private bool PermiteMigrarDados(string tabela)
		{
			return _NoDataTables.ToUpper().IndexOf(TextRaw( TextRaw(tabela.ToUpper()) + "#")) == -1;
		}

		private string CarregaDadosTabela(Tabela tabela)
		{
			string strSel = "";
			string strKey = "";
			string strSep = "";
			string strKeySep = "";
			string[] aKeys = new string[1];
			StringBuilder sRet = new StringBuilder();
			DataTable result = new DataTable();
			foreach (Coluna col in tabela.Colunas)
			{
				strSel += strSep + col.Name ;
				strSep = " ,";
				if (col.IsPrimaryKey)
				{
					if(strKeySep == " , ") Array.Resize(ref aKeys, aKeys.Length+ 1);
					aKeys[aKeys.Length -1 ] = col.Name;
					strKey += strKeySep + col.Name;
					strKeySep = " , ";
				}
			}

			if(TextRaw( tabela.Name) == "T00_Configuracao")
			{
				strSel = strSel + "";
			}

			string query = "select  " + strSel + " from " + tabela.Name + " order by " + (String.IsNullOrEmpty( strKey)? " 1 " : strKey) + ";";
			result = Query(query);
			if (result != null && result.Rows.Count > 0)
			{
				_TablesIdsSorted.Add(TextRaw(tabela.Name), new List<string>());
				if (TableNeedTruncate(tabela))
				{
					sRet.Append("DO $$  BEGIN  " + Environment.NewLine);
					sRet.Append("TRUNCATE TABLE  " + tabela.Name + ";" + Environment.NewLine);
					foreach (DataRow curr in result.Rows)
					{
						sRet.Append(ScriptJustInsert(tabela, curr));
					}
					sRet.Append("END;  $$;  " + Environment.NewLine);
				}
				else
				{
					sRet.Append("DO $$  BEGIN  " + Environment.NewLine);
					foreach (DataRow curr in result.Rows)
					{
						sRet.Append(ScriptLinha(tabela, curr));
					}
					sRet.Append("END;  $$;  " + Environment.NewLine);
				}
				
			}
				
			return sRet.ToString();
		}

		private string ScriptJustInsert(Tabela tabela, DataRow row)
		{
			string strIns = "";
			string strValues = "";
			string strSep = "";
			
			foreach (Coluna col in tabela.Colunas)
			{
				string strVal = row[TextRaw(col.Name)] == DBNull.Value ? "null" : row[TextRaw(col.Name)].ToString();
				strVal = FormataValor(col, strVal);
				strIns += strSep + col.Name;

				strValues += strSep + strVal;
				strSep = " ,";
				
			}

			List<string> dataKeys = _TablesIdsSorted[TextRaw(tabela.Name)];

			string strRet = "       INSERT INTO " + tabela.Name + "  " + Environment.NewLine +
												"       (" + strIns + ")   " + Environment.NewLine +
												"       VALUES(" + strValues + ");  " + Environment.NewLine;

			return strRet;
		}

		private string ScriptLinha(Tabela tabela, DataRow row)
		{
			string strIns = "";
			string strValues = "";
			string strUpd = "";
			string strKey = "";
			string strSep = "";
			string strKeySep = "";
			string strUpdSep = "";
			string strWhereSep = "";
			string strKeyWhere = "";
			foreach (Coluna col in tabela.Colunas)
			{
				string strVal = row[TextRaw(col.Name)]==DBNull.Value ? "null": row[TextRaw(col.Name)].ToString();
				strVal = FormataValor(col, strVal);
				strIns += strSep + col.Name;

				strValues += strSep + strVal;
				strSep = " ,";
				if (col.IsPrimaryKey)
				{
					strKey += strKeySep + col.Name;
					strKeyWhere += strWhereSep + col.Name + " = " + strVal;
					strKeySep = " , ";
					strWhereSep = " and ";
				}
				else 
		    {
					strUpd += strUpdSep + col.Name + " = " + strVal;
					strUpdSep = " , ";
				}
			}

			List<string> dataKeys = _TablesIdsSorted[TextRaw(tabela.Name)];
			dataKeys.Add(strKeyWhere);

			string strRet =   "   IF EXISTS(SELECT " + strKey + " FROM " + tabela.Name + "  WHERE " + strKeyWhere + ")  THEN  " + Environment.NewLine +
												"       UPDATE " + tabela.Name + "   " + Environment.NewLine +
												"       SET " + strUpd + "   " + Environment.NewLine +
												"       WHERE " + strKeyWhere +";  " + Environment.NewLine +
												"   ELSE  " + Environment.NewLine +
												"       INSERT INTO " + tabela.Name + "  " + Environment.NewLine +
												"       (" + strIns +")   " + Environment.NewLine +
												"       VALUES(" + strValues + ");  " + Environment.NewLine +
												"   END IF; " + Environment.NewLine;
			return strRet;
		}

		private bool TableNeedTruncate(Tabela tabela)
		{

			string strUpd = "";
			string strKey = "";

	
			foreach (Coluna col in tabela.Colunas)
			{
				if (col.IsPrimaryKey)
				{
					strKey += col.Name;
				}
				else
				{
					strUpd += col.Name;
				}
			}

			return  (string.IsNullOrEmpty(strKey) || string.IsNullOrEmpty(strUpd));
		}

		private string FormataValor(Coluna col,string valor)
		{

			string ret = "";
			if (valor == "null")
			{
				ret = valor;
			}
			else if ("decimal|numeric|int|bool".IndexOf(col.DataType.Split("(")[0].Trim().ToLower()) > -1)
			{
				ret = valor.Replace(",",".");
			} else if (col.DataType.IndexOf("date") > -1)
			{
				ret = "'" + DateTime.Parse(valor).Year + "-" + DateTime.Parse(valor).Month + "-" + DateTime.Parse(valor).Day + "'";
			}
			else if (col.DataType.IndexOf("timestamp") > -1)
			{
				ret = "'" + DateTime.Parse(valor).Year + "-" + DateTime.Parse(valor).Month + "-" + DateTime.Parse(valor).Day +  "  " + 
					          DateTime.Parse(valor).Hour + ":"  + DateTime.Parse(valor).Minute + ":"  + DateTime.Parse(valor).Second +  "'";
			}
			else
			{
				ret = "'" + valor.Replace("'", "''") + "'";
			}
			return ret;
		}

		/// <summary>
		/// Create a string timestamp from the given DateTime for the database of the instance type.
		/// </summary>
		/// <param name="ts">DateTime.</param>
		/// <returns>A string with timestamp formatted for the database of the instance type.</returns>
		public string Timestamp(DateTime ts)
		{
			switch (_DbType)
			{
				case DbTypes.MsSql:
					return ts.ToString("MM/dd/yyyy hh:mm:ss.fffffff tt");

				case DbTypes.MySql:
					return ts.ToString("yyyy-MM-dd HH:mm:ss.ffffff");

				case DbTypes.PgSql:
					return ts.ToString("MM/dd/yyyy hh:mm:ss.fffffff tt");

				default:
					return null;
			}
		}

		/// <summary>
		/// Sanitize an input string.
		/// </summary>
		/// <param name="val">The value to sanitize.</param>
		/// <returns>A sanitized string.</returns>
		public string SanitizeString(string val)
		{
			if (String.IsNullOrEmpty(val)) return val;

			switch (_DbType)
			{
				case DbTypes.MsSql:
					return MssqlHelper.SanitizeString(val);

				case DbTypes.MySql:
					return MysqlHelper.SanitizeString(val);

				case DbTypes.PgSql:
					return PgsqlHelper.SanitizeString(val);
			}

			throw new Exception("Unknown database type");
		}

		#endregion

		#region Private-Methods

		protected virtual void Dispose(bool disposing)
		{
			if (_Disposed)
			{
				return;
			}

			if (disposing)
			{
				// placeholder
			}

			_Disposed = true;
		}

		private void PopulaConnectionString()
		{
			ConnectionString = "";

			switch (_DbType)
			{
				case DbTypes.MsSql:
					ConnectionString = MssqlHelper.ConnectionString(_ServerIp, _ServerPort, _Username, _Password, _Instance, _DatabaseName);
					break;

				case DbTypes.MySql:
					ConnectionString = MysqlHelper.ConnectionString(_ServerIp, _ServerPort, _Username, _Password, _DatabaseName);
					break;

				case DbTypes.PgSql:
					ConnectionString = PgsqlHelper.ConnectionString(_ServerIp, _ServerPort, _Username, _Password, _DatabaseName);
					break;
			}

			return;
		}

		private void CarregaTabelas()
		{
			lock (_LoadingTablesLock)
			{
				string query = "";
				DataTable result = new DataTable();

				#region Build-Query

				switch (_DbType)
				{
					case DbTypes.MsSql:
						query = MssqlHelper.LoadTableNamesQuery(_DatabaseName);
						break;

					case DbTypes.MySql:
						query = MysqlHelper.LoadTableNamesQuery();
						break;

					case DbTypes.PgSql:
						query = PgsqlHelper.LoadTableNamesQuery();
						break;
				}

				#endregion

				#region Process-Results

				result = Query(query);
				List<string> tableNames = new List<string>();

				if (result != null && result.Rows.Count > 0)
				{
					switch (_DbType)
					{
						case DbTypes.MsSql:
							foreach (DataRow curr in result.Rows)
							{
								tableNames.Add(curr["TABLE_NAME"].ToString());
							}
							break;

						case DbTypes.MySql:
							foreach (DataRow curr in result.Rows)
							{
								tableNames.Add(curr["Tables_in_" + _DatabaseName].ToString());
							}
							break;

						case DbTypes.PgSql:
							foreach (DataRow curr in result.Rows)
							{
								tableNames.Add(curr["tablename"].ToString());
							}
							break;
					}
				}

				if (tableNames != null && tableNames.Count > 0)
				{
					_TableNames = new ListaConcorrente<string>();
					foreach (string curr in tableNames)
					{
						_TableNames.Add(curr);
					}
				}

				#endregion

				return;
			}
		}

		private void CarregaDetalhesTabela()
		{
			lock (_LoadingTablesLock)
			{
				string query = "";
				DataTable result = new DataTable();
				Dictionary<string, List<Coluna>> tableDetails = new Dictionary<string, List<Coluna>>();


				foreach (string currTable in _TableNames)
				{
					#region Gather-Schema

					List<Coluna> columns = new List<Coluna>();
					List<Constraint> mReferrencias = new List<Constraint>();

					switch (_DbType)
					{
						case DbTypes.MsSql:
							query = MssqlHelper.LoadTableColumnsQuery(_DatabaseName, currTable);
							break;

						case DbTypes.MySql:
							query = MysqlHelper.LoadTableColumnsQuery(_DatabaseName, currTable);
							break;

						case DbTypes.PgSql:
							query = PgsqlHelper.LoadTableColumnsQuery(_DatabaseName, currTable);
							break;
					}

					#endregion

					#region Process-Schema

					result = Query(query);
					if (result != null && result.Rows.Count > 0)
					{
						foreach (DataRow currColumn in result.Rows)
						{
							#region Process-Each-Column

							/*
							public bool IsPrimaryKey;
							public string Name;
							public string DataType;
							public int? MaxLength;
							public bool Nullable;
							*/
							Coluna tempColumn = new Coluna();
							int maxLength = 0;

							switch (_DbType)
							{
								case DbTypes.MsSql:
									#region Mssql

									tempColumn.Name = currColumn["COLUMN_NAME"].ToString();
									if (currColumn["CONSTRAINT_NAME"].ToString().StartsWith("PK_")) tempColumn.IsPrimaryKey = true;
									else tempColumn.IsPrimaryKey = false;
									tempColumn.DataType = currColumn["DATA_TYPE"].ToString();
									if (!Int32.TryParse(currColumn["CHARACTER_MAXIMUM_LENGTH"].ToString(), out maxLength)) { tempColumn.MaxLength = null; }
									else tempColumn.MaxLength = maxLength;
									if (String.Compare(currColumn["IS_NULLABLE"].ToString(), "YES") == 0) tempColumn.Nullable = true;
									else tempColumn.Nullable = false;
									break;

								#endregion

								case DbTypes.MySql:
									#region Mysql

									tempColumn.Name = currColumn["COLUMN_NAME"].ToString();
									if (String.Compare(currColumn["COLUMN_KEY"].ToString(), "PRI") == 0) tempColumn.IsPrimaryKey = true;
									else tempColumn.IsPrimaryKey = false;
									tempColumn.DataType = currColumn["DATA_TYPE"].ToString();
									if (!Int32.TryParse(currColumn["CHARACTER_MAXIMUM_LENGTH"].ToString(), out maxLength)) { tempColumn.MaxLength = null; }
									else tempColumn.MaxLength = maxLength;
									if (String.Compare(currColumn["IS_NULLABLE"].ToString(), "YES") == 0) tempColumn.Nullable = true;
									else tempColumn.Nullable = false;
									break;

								#endregion

								case DbTypes.PgSql:
									#region Pgsql

									tempColumn.Name = "\"" + currColumn["column_name"].ToString() + "\"";
									if (String.Compare(currColumn["is_primary_key"].ToString(), "YES") == 0) tempColumn.IsPrimaryKey = true;
									else tempColumn.IsPrimaryKey = false;
									tempColumn.DataType = currColumn["DATA_TYPE"].ToString();
									if (!Int32.TryParse(currColumn["max_len"].ToString(), out maxLength)) { tempColumn.MaxLength = null; }
									else tempColumn.MaxLength = maxLength;
									if (String.Compare(currColumn["IS_NULLABLE"].ToString(), "YES") == 0) tempColumn.Nullable = true;
									else tempColumn.Nullable = false;
									if (string.IsNullOrEmpty( currColumn["column_default"].ToString())) tempColumn.Default = "";
									else tempColumn.Default = currColumn["column_default"].ToString();
									break;

									#endregion
							}

							columns.Add(tempColumn);

							#endregion
						}

						tableDetails.Add(currTable, columns);



						switch (_DbType)
						{
							case DbTypes.MsSql:
								query = "";
								break;

							case DbTypes.MySql:
								query = "";
								break;

							case DbTypes.PgSql:
								query = PgsqlHelper.LoadConstraintQuery(_DatabaseName, currTable);
								break;
						}

						if (!string.IsNullOrEmpty(query))
						{
							result = Query(query);
							if (result != null && result.Rows.Count > 0)
							{
								foreach (DataRow currColumn in result.Rows)
								{
									#region Process-Each-Column


									Constraint tempConstraint = new Constraint();


									switch (_DbType)
									{
										case DbTypes.MsSql:
											#region Mssql


											break;

										#endregion

										case DbTypes.MySql:
											#region Mysql

											break;

										#endregion

										case DbTypes.PgSql:
											#region Pgsql

											tempConstraint.Name = "\"" + currColumn["constraint_name"].ToString() + "\"";
											tempConstraint.ForeignTable = "\"" + currColumn["foreign_table_name"].ToString() + "\"";
											tempConstraint.ForeignColumns = "\"" + currColumn["foreign_column_name"].ToString() + "\"";
											tempConstraint.LocalColumns = "\"" + currColumn["column_name"].ToString() + "\"";
											tempConstraint.Type = currColumn["constraint_type"].ToString();

											break;

											#endregion
									}
									mReferrencias.Add(tempConstraint);
									#endregion
								}
							}
						}
					}
					mTabelas.Add(new Tabela("\"" + currTable + "\"" , columns, mReferrencias));
					#endregion
				}

				#region Replace-Table-Details

				_TableDetails = new ConcurrentDictionary<string, List<Coluna>>();
				foreach (KeyValuePair<string, List<Coluna>> curr in tableDetails)
				{
					_TableDetails.TryAdd(curr.Key, curr.Value);
				}

				#endregion

				return;
			}
		}

		private void CarregaProcedures()
		{

			string query = "";


			#region Build-Query

			switch (_DbType)
			{
				case DbTypes.MsSql:
					query = "";
					break;

				case DbTypes.MySql:
					query = "";
					break;

				case DbTypes.PgSql:
					query = PgsqlHelper.LoadFunctionsDefinitionQuery();
					break;
			}

			#endregion

			#region Process-Results

			if (!string.IsNullOrEmpty(query))
			{
				DataTable result;
				result = Query(query);
				

				if (result != null && result.Rows.Count > 0)
				{
					switch (_DbType)
					{
						case DbTypes.MsSql:

							break;

						case DbTypes.MySql:

							break;

						case DbTypes.PgSql:
							foreach (DataRow curr in result.Rows)
							{
								if(curr["definition"].ToString().ToUpper().IndexOf("AS $FUNCTION$") > 0)
								{
									mProcedures.Add(new Procedure(curr["fname"].ToString(), curr["definition"].ToString()));
								}
							}
							break;
					}
				}
			}

			#endregion

			return;

		}

		private void CarregaDependencias()
		{
			lock (_LoadingTablesLock)
			{
				string query1= "";
				string query2 = "";
				DataTable result = new DataTable();

				#region Build-Query

				switch (_DbType)
				{
					case DbTypes.MsSql:
						//query1 = MssqlHelper.LoadTableNamesQuery(_DatabaseName); //Implementar
						break;

					case DbTypes.MySql:
						//query1 = MysqlHelper.LoadTableNamesQuery(); //Implementar
						break;

					case DbTypes.PgSql:
						query1 = PgsqlHelper.LoadTempTableDependency();
						query2 = PgsqlHelper.LoadTableDependencies();
						break;
				}

				#endregion

				#region Process-Results
				if (_DbType == DbTypes.PgSql)
				{
					result = QueryDependency(query1, query2);
				}
				else
				{
					result = Query(query1); //Prepara Tabela Temporária
				}	

				List<string> tableNames = new List<string>();

				if (result != null && result.Rows.Count > 0)
				{
					switch (_DbType)
					{
						case DbTypes.MsSql:
							foreach (DataRow curr in result.Rows)
							{
								tableNames.Add(curr["TABLE_NAME"].ToString());
							}
							break;

						case DbTypes.MySql:
							foreach (DataRow curr in result.Rows)
							{
								tableNames.Add(curr["Tables_in_" + _DatabaseName].ToString());
							}
							break;

						case DbTypes.PgSql:
							foreach (DataRow curr in result.Rows)
							{
								tableNames.Add(curr["OnTableName"].ToString());
							}
							break;
					}
				}

				if (tableNames != null && tableNames.Count > 0)
				{
					_TableDependencies = new ListaConcorrente<string>();
					foreach (string curr in tableNames)
					{
						_TableDependencies.Add(curr);
					}
				}

				#endregion

				return;
			}
		}

		private void OrdenaDependncias()
		{
			_TableDependencies = new ListaConcorrente<string>();
			foreach (Tabela tabDef in mTabelas)
			{
				_TableDependencies.Add(TextRaw(tabDef.Name));
			}

		}

		private string PreparedFieldname(string s)
		{
			switch (_DbType)
			{
				case DbTypes.MsSql:
					return s;

				case DbTypes.MySql:
					return s;

				case DbTypes.PgSql:
					return "\"" + s + "\"";
			}

			return null;
		}

		private string PreparedStringValue(string s)
		{
			switch (_DbType)
			{
				case DbTypes.MsSql:
					return "'" + MssqlHelper.SanitizeString(s) + "'";

				case DbTypes.MySql:
					return "'" + MysqlHelper.SanitizeString(s) + "'";

				case DbTypes.PgSql:
					// uses $xx$ escaping
					return PgsqlHelper.SanitizeString(s);
			}

			return null;
		}

		private string PreparedUnicodeValue(string s)
		{
			switch (_DbType)
			{
				case DbTypes.MsSql:
					return "N" + PreparedStringValue(s);

				case DbTypes.MySql:
					return "N" + PreparedStringValue(s);

				case DbTypes.PgSql:
					return "U&" + PreparedStringValue(s);
			}

			return null;
		}


		/// <summary>
		/// Execute a query.
		/// </summary>
		/// <param name="query">Database query defined outside of the database client.</param>
		/// <returns>A DataTable containing the results.</returns>
		private DataTable Query(string query)
		{
			if (String.IsNullOrEmpty(query)) throw new ArgumentNullException(query);
			DataTable result = new DataTable();

			if (DebugRawQuery) Console.WriteLine("RawQuery: " + query);

			switch (_DbType)
			{
				case DbTypes.MsSql:
					#region Mssql

					using (SqlConnection conn = new SqlConnection(ConnectionString))
					{
						conn.Open();
						SqlDataAdapter sda = new SqlDataAdapter(query, conn);
						sda.Fill(result);
						conn.Dispose();
						conn.Close();
					}

					break;

				#endregion

				case DbTypes.MySql:
					#region Mysql

					using (MySqlConnection conn = new MySqlConnection(ConnectionString))
					{
						conn.Open();
						MySqlCommand cmd = new MySqlCommand();
						cmd.Connection = conn;
						cmd.CommandText = query;
						MySqlDataAdapter sda = new MySqlDataAdapter(cmd);
						DataSet ds = new DataSet();
						sda.Fill(ds);
						if (ds != null)
						{
							if (ds.Tables != null)
							{
								if (ds.Tables.Count > 0)
								{
									result = ds.Tables[0];
								}
							}
						}

						conn.Close();
					}

					break;

				#endregion

				case DbTypes.PgSql:
					#region Pgsql

					using (NpgsqlConnection conn = new NpgsqlConnection(ConnectionString))
					{
						conn.Open();
						NpgsqlDataAdapter da = new NpgsqlDataAdapter(query, conn);
						DataSet ds = new DataSet();
						da.Fill(ds);

						if (ds != null && ds.Tables != null && ds.Tables.Count > 0)
						{
							result = ds.Tables[0];
						}

						conn.Close();
					}

					break;

					#endregion
			}

			if (DebugResultRowCount)
			{
				if (result != null) Console.WriteLine("RawQuery: returning " + result.Rows.Count + " row(s)");
				else Console.WriteLine("RawQery: returning null");
			}

			return result;
		}


		/// <summary>
		/// Execute a query.
		/// </summary>
		/// <param name="query">Database query defined outside of the database client.</param>
		/// <returns>A DataTable containing the results.</returns>
		private DataTable QueryDependency(string query1, string query2)
		{
			if (String.IsNullOrEmpty(query1)) throw new ArgumentNullException(query1);
			DataTable result = new DataTable();

			if (DebugRawQuery) Console.WriteLine("RawQuery: " + query1);

			switch (_DbType)
			{
				case DbTypes.MsSql:
					#region Mssql

					using (SqlConnection conn = new SqlConnection(ConnectionString))
					{
						conn.Open();
						SqlDataAdapter sda = new SqlDataAdapter(query1, conn);
						sda.Fill(result);
						conn.Dispose();
						conn.Close();
					}

					break;

				#endregion

				case DbTypes.MySql:
					#region Mysql

					using (MySqlConnection conn = new MySqlConnection(ConnectionString))
					{
						conn.Open();
						MySqlCommand cmd = new MySqlCommand();
						cmd.Connection = conn;
						cmd.CommandText = query1;
						MySqlDataAdapter sda = new MySqlDataAdapter(cmd);
						DataSet ds = new DataSet();
						sda.Fill(ds);
						if (ds != null)
						{
							if (ds.Tables != null)
							{
								if (ds.Tables.Count > 0)
								{
									result = ds.Tables[0];
								}
							}
						}

						conn.Close();
					}

					break;

				#endregion

				case DbTypes.PgSql:
					#region Pgsql

					using (NpgsqlConnection conn = new NpgsqlConnection(ConnectionString))
					{
						conn.Open();
						NpgsqlCommand cmd = new NpgsqlCommand(query1, conn);
						cmd.ExecuteNonQuery();
						NpgsqlDataAdapter da = new NpgsqlDataAdapter(query2, conn);
						DataSet ds = new DataSet();
						da.Fill(ds);

						if (ds != null && ds.Tables != null && ds.Tables.Count > 0)
						{
							result = ds.Tables[0];
						}

						conn.Close();
					}

					break;

					#endregion
			}

			if (DebugResultRowCount)
			{
				if (result != null) Console.WriteLine("RawQuery: returning " + result.Rows.Count + " row(s)");
				else Console.WriteLine("RawQery: returning null");
			}

			return result;
		}

		private void NoQueryy(string query)
		{
			if (String.IsNullOrEmpty(query)) throw new ArgumentNullException(query);
			

			if (DebugRawQuery) Console.WriteLine("RawQuery: " + query);

			switch (_DbType)
			{
				case DbTypes.MsSql:
					#region Mssql

					//Implementar

					break;

				#endregion

				case DbTypes.MySql:
					#region Mysql

					//Implementar

					break;

				#endregion

				case DbTypes.PgSql:
					#region Pgsql

					using (NpgsqlConnection conn = new NpgsqlConnection(ConnectionString))
					{
						conn.Open();
						NpgsqlCommand cmd = new NpgsqlCommand(query, conn);
						cmd.ExecuteNonQuery();

						conn.Close();
					}

					break;

					#endregion
			}

			if (DebugResultRowCount)
			{
				
				 Console.WriteLine("NoQery: returns void");
			}

		}

		#endregion

		#region Public-Static-Methods

		/// <summary>
		/// Convert a DateTime to a string formatted for the specified database type.
		/// </summary>
		/// <param name="dbType">The type of database.</param>
		/// <param name="dt">The timestamp.</param>
		/// <returns>A string formatted for use with the specified database.</returns>
		public static string DbTimestamp(DbTypes dbType, DateTime ts)
		{
			switch (dbType)
			{
				case DbTypes.MsSql:
				case DbTypes.PgSql:
					return ts.ToString("MM/dd/yyyy hh:mm:ss.fffffff tt");

				case DbTypes.MySql:
					return ts.ToString("yyyy-MM-dd HH:mm:ss.ffffff");

				default:
					return null;
			}
		}

		/// <summary>
		/// Convert a DateTime to a string formatted for the specified database type.
		/// </summary>
		/// <param name="dbType">The type of database.</param>
		/// <param name="dt">The timestamp.</param>
		/// <returns>A string formatted for use with the specified database.</returns>
		public static string DbTimestamp(string dbType, DateTime ts)
		{
			if (String.IsNullOrEmpty(dbType)) throw new ArgumentNullException(nameof(dbType));
			switch (dbType.ToLower())
			{
				case "mssql":
					return DbTimestamp(DbTypes.MsSql, ts);

				case "mysql":
					return DbTimestamp(DbTypes.MySql, ts);

				case "pgsql":
					return DbTimestamp(DbTypes.PgSql, ts);

				default:
					throw new ArgumentOutOfRangeException(nameof(dbType));
			}
		}

		#endregion
	}
}

